### ISSUE TITLE
Showing wrong indoor temperature.

### ISSUE THREAD

**Issue by sonybansi** [pedobry/esphome_toshiba_suzumi#12]
**The indoor temperature is showing incorrectly (currently 127°C). I have tried using it with and without the outdoor temperature filters, but there is no change.** 

Indoor unit- RAS-35G2KVP-ND
Outdoor unit- RAS-35G2AVP-ND
esp32 devkit v1

![Screenshot 2024-11-29 at 00 42 53](https://github.com/user-attachments/assets/608d78d0-4558-494d-bea5-b50a94960879)

**Log >**
```
[00:44:01][I][app:100]: ESPHome version 2024.11.2 compiled on Nov 29 2024, 00:36:37
[00:44:01][I][ToshibaClimateUart:315]: Min Temp: 17
[00:45:00][I][ToshibaClimateUart:125]: Requesting data from sensor 187, checksum: 249
[00:45:00][I][ToshibaClimateUart:125]: Requesting data from sensor 190, checksum: 246
[00:45:00][I][ToshibaClimateUart:257]: Received room temp: 127 °C
[00:45:00][I][ToshibaClimateUart:262]: Received outdoor temp: -8 °C
```
**ESPHome config file >**
```
esphome:
  name: toshiba
  friendly_name: Toshiba

esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
captive_portal:

external_components:
  - source: 
      type: git
      url: https://github.com/pedobry/esphome_toshiba_suzumi
    components: [toshiba_suzumi]

logger:
  level: info

uart:
  id: uart_bus
  tx_pin: 33
  rx_pin: 32
  parity: EVEN
  baud_rate: 9600

climate:
  - platform: toshiba_suzumi
    name: living-room
    id: living_room
    uart_id: uart_bus
    outdoor_temp:        # Optional. Outdoor temperature sensor
      name: Outdoor Temp
      #filters:
        # Filter out value 127 as that's what unit sends when it can's measure the outside temp.
       # - filter_out: 127 
    power_select:
      name: "Power level"
    #min_temp: 7 # Optional. Min temp is by default set to 17°C. If your AC has 8° heating mode, you can set different min temperature here.
    horizontal_swing: true # Optional. Uncomment if your HVAC supports also horizontal swing
    special_mode:          # Optional. Enable only the features your HVAC supports.
      name: "Special mode"
      modes:
        #- "Off"
        #- "ECO"
        - "Hi POWER"
        #- "8 degrees"
        #- "Fireplace"
    #disable_wifi_led: true # Optional. Disable Wifi LED on internal unit.

# Enable button to scan for unknown values in AC unit. This is optional.
button:
  - platform: template
    name: "Scan for unknown sensors"
    icon: "mdi:reload"
    on_press:
      then:
        - lambda: |-
            auto* controller = static_cast<toshiba_suzumi::ToshibaClimateUart*>(id(living_room));
            controller->scan();
```
